import { useSession } from 'next-auth/react'
import Head from 'next/head'
import { useRouter } from 'next/router'
import { ReactElement } from 'react'
import Layout from '../components/Layout'
import type { NextPageWithLayout } from './_app'

const OverlaysPage: NextPageWithLayout = () => {
  const { push } = useRouter()
  const { status } = useSession()
  if (status === 'loading') {
    return <p>Loading...</p>
  }
  if (status === 'unauthenticated') {
    push('/api/auth/signin')
  }

  return (
    <>
      <Head>
        <title>Overlays | GnomeBoard</title>
        <meta name='description' content='Generated by create-t3-app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
    </>
  )
}

OverlaysPage.getLayout = function getLayout(page: ReactElement) {
  return <Layout>{page}</Layout>
}

export default OverlaysPage
