import { useSession } from 'next-auth/react'
import Head from 'next/head'
import { useRouter } from 'next/router'
import { ReactElement } from 'react'
import Layout from '../components/Layout'
import { trpc } from '../utils/trpc'
import type { NextPageWithLayout } from './_app'

const SchedulePage: NextPageWithLayout = () => {
  const hello = trpc.useQuery(['example.hello', { text: 'from tRPC' }])
  const { push } = useRouter()
  const { status } = useSession()
  if (status === 'loading') {
    return <p>Loading...</p>
  }
  if (status === 'unauthenticated') {
    push('/api/auth/signin')
  }

  return (
    <>
      <Head>
        <title>Schedule | GnomeBoard</title>
        <meta name='description' content='Generated by create-t3-app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <div className='pt-6 text-2xl text-blue-500 flex justify-center items-center w-full'>
        {hello.data ? <p>{hello.data.greeting}</p> : <p>Loading..</p>}
      </div>
    </>
  )
}

SchedulePage.getLayout = function getLayout(page: ReactElement) {
  return <Layout>{page}</Layout>
}

export default SchedulePage
