import Head from 'next/head'
import { ReactElement } from 'react'
import Layout from '../components/Layout'
import { trpc } from '../utils/trpc'
import type { NextPageWithLayout } from './_app'

const SettingsPage: NextPageWithLayout = () => {
  const hello = trpc.useQuery(['example.hello', { text: 'from tRPC' }])

  return (
    <>
      <Head>
        <title>Settings | GnomeBoard</title>
        <meta name='description' content='Generated by create-t3-app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <div className='pt-6 text-2xl text-blue-500 flex justify-center items-center w-full'>
        {hello.data ? <p>{hello.data.greeting}</p> : <p>Loading..</p>}
      </div>
    </>
  )
}

SettingsPage.getLayout = function getLayout(page: ReactElement) {
  return <Layout>{page}</Layout>
}

export default SettingsPage
