import { ClerkProvider } from '@/components/clerk-provider';
import { ThemeProvider } from '@/components/theme-provider';
import type { Metadata } from 'next';
import type { CSSProperties, ReactNode } from 'react';
import './globals.css';
import ConvexClientProvider from '@/components/convex-client-provider';
import { Providers } from './providers';

export const metadata: Metadata = {
  title: 'Clerk Next.js Quickstart',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: ReactNode;
}>) {
  return (
    <html
      lang='en'
      className='h-full'
      suppressHydrationWarning
      style={{ '--font-satoshi': '"Satoshi", sans-serif' } as CSSProperties}
    >
      <head>
        <link
          rel='stylesheet'
          href='https://api.fontshare.com/v2/css?f[]=satoshi@1,2,3,4,5,6,7,8,9&display=swap'
        />
      </head>
      <body className='flex min-h-full flex-col antialiased font-sans'>
        <ClerkProvider>
          <ThemeProvider
            attribute='class'
            defaultTheme='system'
            enableSystem
            disableTransitionOnChange
          >
            <Providers>
              <ConvexClientProvider>{children}</ConvexClientProvider>
            </Providers>
          </ThemeProvider>
        </ClerkProvider>
      </body>
    </html>
  );
}
