import type { Metadata } from 'next';
import type { CSSProperties, ReactNode } from 'react';
import './globals.css';
import { Providers } from './providers';

export const metadata: Metadata = {
  title: 'Clerk Next.js Quickstart',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: ReactNode;
}>) {
  return (
    <html
      lang='en'
      className='h-full'
      suppressHydrationWarning
      style={
        { '--font-satoshi': '"Satoshi", sans-serif' } as CSSProperties
      }
    >
      <head>
        <link
          rel='stylesheet'
          href='https://api.fontshare.com/v2/css?f[]=satoshi@1,2,3,4,5,6,7,8,9&display=swap'
        />
      </head>
      <body className='flex min-h-full flex-col antialiased font-sans'>
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
